name: Run my python
on:
    push:

jobs:
    build: 
        name: do job1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run send_mail.py
          run:
            python3 send_mail.py
    build2:
        name: dp job2
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run test2.py
          run:
            python3 test2.py